### PR TITLE
Get rid of method overriding in policies

### PR DESCRIPTION
**Pull request by AlbertGazizov**
Just wanted to make the code a bit more readable, since it's hard to understand and debug it when the logic is not sequential.

### Review

- [ ] Document code according to [Getting Started with Yard](http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md).
- [ ] All tests are passing.
- [ ] Test manually.
- [ ] Get approval.

### Pre-merge checklist

- [ ] The PR relates to a single subject with a clear title and description in grammatically correct, complete sentences.
- [ ] Verify that feature branch is up-to-date with `master` (if not - rebase it).
- [ ] Double check the quality of [commit messages](http://chris.beams.io/posts/git-commit/).
- [ ] Squash related commits together.

### CODE REVIEW

**Comment by pirj** [comment]
Some were sceptical regarding baking the policies in. This is making it harder to extract by spreading it all over.

**Comment by AlbertGazizov** [comment]
> Some were sceptical regarding baking the policies in. This is making it harder to extract by spreading it all over.

Could you clarify please? What extraction do you mean?

**Comment by pirj** [comment]
If we happen to decide that policies should be made optional, and allow the user to decide whether include them or not.

**Comment by AlbertGazizov** [comment]
> If we happen to decide that policies should be made optional, and allow the user to decide whether include them or not.

Now when you read the `perform` method definition you don’t expect that some another code could be executed when you run it. What makes this code hard to understand and maintain(if you change this method you should remember that it is overridden in another file). 
Basically the method overriding is not a good way to make code extendable.
The alternative to make it extendable(optional) is to introduce hooks. In case of hooks the `perform` will look something like this:
```ruby
def perform!(context: nil, **options) 
  run_hooks(:before_transaction) # this will policies
  transaction do
    validate!(context) 
    perform_action!(**options) 
  end
end
```
So that the policies will become optional and at the same time they will be executed sequentially.
But until it's decided to make it optional I don’t see a reason to introduce hooks, so that it’s more right(IMHO) to make it as simple and clean as possible just by calling policies in the place we will run hooks in the future, what I actually did in this PR. 
WDYT?

**Comment by pirj** [comment]
I can only argue with the point that overriding is not good, if you set a breakpoint in `ActiveRecord::Base#save!`, you'll see a long list of `lib/active_record/validations.rb`, `lib/active_record/persistence.rb`, `lib/active_record/suppressor.rb`, `lib/active_record/transactions.rb`.
I believe with callbacks it would be harder to control the order of the nesting.

In a dynamic language like Ruby you may expect any kinds of monkey patches and extensions to plug in between the caller and what it expects to call.

**Comment by AlbertGazizov** [comment]
> I can only argue with the point that overriding is not good, if you set a breakpoint in `ActiveRecord::Base#save!`, you'll see a long list of `lib/active_record/validations.rb`, `lib/active_record/persistence.rb`, `lib/active_record/suppressor.rb`, `lib/active_record/transactions.rb`.

Right, and it doesn't mean that this code is a good code) Or at least that we can't apply a better solution.

> I believe with callbacks it would be harder to control the order of the nesting.

I don't think so, you register callbacks sequentially, so the order will be preserved.
Actually, callbacks will give more flexibility for ordering because they allow to introduce multiple hooks inside the `perform`. 

> In a dynamic language like Ruby you may expect any kinds of monkey patches and extensions to plug in between the caller and what it expects to call.

Yes, Ruby is a very flexible language and we can do a lot of things we can't do in other languages, but it doesn't mean that we should use them if they make code harder to understand and maintain.

**Comment by pirj** [comment]
With callbacks, you can prepend your callback, but it would be harder to push it somewhere in the middle of, say, validations before transactions.

I think I don't exactly understand the issue you were facing. Can you please elaborate what is improved by this change?

**Pull request closed without merging**
